# Generated by Django 3.2.6 on 2021-08-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Recorder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recorders.brand")),
            ],
            options={
                "verbose_name_plural": "Recorders",
            },
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["name"], name="recorders_b_name_218827_idx"),
        ),
        migrations.AddIndex(
            model_name="recorder",
            index=models.Index(fields=["model"], name="recorders_r_model_1589ad_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recorder",
            unique_together={("model", "brand")},
        ),
    ]
