# Generated by Django 3.2.6 on 2021-08-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
