# Generated by Django 3.2.6 on 2021-08-18 13:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recorders", "0002_alter_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slug",
            field=autoslug.fields.AutoSlugField(default="", editable=False, populate_from="name", unique=True),
        ),
        migrations.AddField(
            model_name="recorder",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="", editable=False, populate_from=models.CharField(max_length=100)
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(default="", max_length=100, unique=True),
        ),
    ]
