# Generated by Django 3.2.6 on 2021-08-18 14:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recorders", "0003_auto_20210818_1357"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recorder",
            name="slug",
            field=autoslug.fields.AutoSlugField(default="", editable=False, populate_from="model"),
        ),
    ]
