# Generated by Django 3.2.6 on 2021-10-08 13:53

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recorders', '0004_alter_recorder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='recorders/recorder_placeholder.gif', upload_to='recorders'),
        ),
    ]
