# Generated by Django 3.2.6 on 2021-10-08 15:01

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recorders', '0005_recorder_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='brands/brand_placeholder.gif', upload_to='brands'),
        ),
    ]
